import { type Review } from "./types";

export const MEDIA_REVIEWS_VIDEOS: Review[] = [
  {
    id: "1",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://picsum.photos/seed/r1/120/120",
    review_by: "Erin Torff",
    avatar: "https://i.pravatar.cc/40?img=1",
    date: "11-11-2023",
    rating: 4,
    review:
      "This portable blender is a game changer! It's compact, easy to use, and powerful enough to blend smoothies, protein shakes, and even ice. The rechargeable battery lasts a long time, making it perfect for on-the-go use.",
  },
  {
    id: "2",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://picsum.photos/seed/r2/120/120",
    review_by: "Zain Safi",
    avatar: "https://i.pravatar.cc/40?img=2",
    date: "11-11-2023",
    rating: 5,
    review:
      "Absolutely love this product! The build quality is excellent and it's very easy to use. Highly recommended for anyone looking for a reliable blender.",
  },
  {
    id: "3",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://picsum.photos/seed/r3/120/120",
    review_by: "Sarah Chen",
    avatar: "https://i.pravatar.cc/40?img=3",
    date: "10-11-2023",
    rating: 4,
    review: "Great value for money. Works exactly as described and the battery life is impressive.",
  },
  {
    id: "4",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://picsum.photos/seed/r4/120/120",
    review_by: "Mike Johnson",
    avatar: "https://i.pravatar.cc/40?img=4",
    date: "09-11-2023",
    rating: 5,
    review: "Best purchase I've made this year. Super compact and powerful!",
  },
  {
    id: "5",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://picsum.photos/seed/r5/120/120",
    review_by: "Emma Wilson",
    avatar: "https://i.pravatar.cc/40?img=5",
    date: "08-11-2023",
    rating: 3,
    review: "Decent product, does what it says. Shipping was fast too.",
  },
  {
    id: "6",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://picsum.photos/seed/r6/120/120",
    review_by: "Ali Hassan",
    avatar: "https://i.pravatar.cc/40?img=6",
    date: "07-11-2023",
    rating: 5,
    review: "Incredible quality for the price. Very happy with this purchase.",
  },
  {
    id: "7",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://picsum.photos/seed/r7/120/120",
    review_by: "Nadia Malik",
    avatar: "https://i.pravatar.cc/40?img=7",
    date: "06-11-2023",
    rating: 4,
    review: "Really solid build. I use it every day and it hasn't let me down once.",
  },
  {
    id: "8",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://picsum.photos/seed/r8/120/120",
    review_by: "James Park",
    avatar: "https://i.pravatar.cc/40?img=8",
    date: "05-11-2023",
    rating: 5,
    review: "Fast delivery and the product exceeded my expectations. Will buy again!",
  },
  {
    id: "9",
    url: "https://www.w3schools.com/html/mov_bbb.mp4",
    thumbnail: "https://picsum.photos/seed/r9/120/120",
    review_by: "Layla Ahmed",
    avatar: "https://i.pravatar.cc/40?img=9",
    date: "04-11-2023",
    rating: 4,
    review: "Good product overall. The packaging was neat and it arrived on time.",
  },
];
