import type { Review, RatingBar } from "@/features/all-review/types";

export const RATING_DISTRIBUTION: RatingBar[] = [
  { stars: 5, value: 100 },
  { stars: 4, value: 80 },
  { stars: 3, value: 60 },
  { stars: 2, value: 30 },
  { stars: 1, value: 5 },
];

export const ALL_REVIEWS_DATA: Review[] = [
  {
    id: 1,
    name: "Zain Saris",
    date: "11-11-2023",
    verified: true,
    rating: 4.5,
    text: "I absolutely love this smartwatch! It tracks my steps, heart rate, and even sleep patterns with great accuracy. The design is sleek and lightweight, making it comfortable to wear all day. The battery lasts several days, and the notifications from my phone come through perfectly.",
    hasMedia: true,
    videoIndex: 0,
    avatar: 1,
  },
  {
    id: 2,
    name: "Erin Torff",
    date: "11-11-2023",
    verified: false,
    rating: 4.5,
    text: "This portable blender is a game changer! It's compact, easy to use, and powerful enough to blend smoothies, protein shakes, and even ice. The rechargeable battery lasts a long time, making it perfect for on-the-go use.",
    hasMedia: false,
    avatar: 2,
  },
  {
    id: 3,
    name: "Zain Saris",
    date: "11-11-2023",
    verified: true,
    rating: 4.5,
    text: "I absolutely love this smartwatch! It tracks my steps, heart rate, and even sleep patterns with great accuracy. The design is sleek and lightweight, making it comfortable to wear all day. The battery lasts several days, and the notifications from my phone come through perfectly.",
    hasMedia: true,
    videoIndex: 1,
    avatar: 3,
  },
  {
    id: 4,
    name: "Wilson Workman",
    date: "11-11-2023",
    verified: false,
    rating: 4.5,
    text: "I'm so impressed with this LED desk lamp! It has multiple brightness settings and an adjustable arm, making it perfect for reading, studying, or working late at night. The touch controls are super convenient, and the light is easy on the eyes.",
    hasMedia: false,
    avatar: 4,
  },
  {
    id: 5,
    name: "Zain Saris",
    date: "11-11-2023",
    verified: true,
    rating: 4.5,
    text: "I absolutely love this smartwatch! It tracks my steps, heart rate, and even sleep patterns with great accuracy. The design is sleek and lightweight, making it comfortable to wear all day. The battery lasts several days, and the notifications from my phone come through perfectly.",
    hasMedia: true,
    videoIndex: 2,
    avatar: 5,
  },
  {
    id: 6,
    name: "Zain Saris",
    date: "11-11-2023",
    verified: true,
    rating: 4.5,
    text: "I absolutely love this smartwatch! It tracks my steps, heart rate, and even sleep patterns with great accuracy. The design is sleek and lightweight, making it comfortable to wear all day. The battery lasts several days, and the notifications from my phone come through perfectly.",
    hasMedia: true,
    videoIndex: 3,
    avatar: 6,
  },
  {
    id: 7,
    name: "Erin Torff",
    date: "11-11-2023",
    verified: false,
    rating: 4.5,
    text: "This portable blender is a game changer! It's compact, easy to use, and powerful enough to blend smoothies, protein shakes, and even ice. The rechargeable battery lasts a long time, making it perfect for on-the-go use.",
    hasMedia: false,
    avatar: 7,
  },
  {
    id: 8,
    name: "Zain Saris",
    date: "11-11-2023",
    verified: true,
    rating: 4.5,
    text: "I absolutely love this smartwatch! It tracks my steps, heart rate, and even sleep patterns with great accuracy. The design is sleek and lightweight, making it comfortable to wear all day. The battery lasts several days, and the notifications from my phone come through perfectly.",
    hasMedia: true,
    videoIndex: 4,
    avatar: 8,
  },
  {
    id: 9,
    name: "Wilson Workman",
    date: "11-11-2023",
    verified: false,
    rating: 4.5,
    text: "I'm so impressed with this LED desk lamp! It has multiple brightness settings and an adjustable arm, making it perfect for reading, studying, or working late at night. The touch controls are super convenient, and the light is easy on the eyes.",
    hasMedia: false,
    avatar: 9,
  },
  {
    id: 10,
    name: "Zain Saris",
    date: "11-11-2023",
    verified: true,
    rating: 4.5,
    text: "I absolutely love this smartwatch! It tracks my steps, heart rate, and even sleep patterns with great accuracy. The design is sleek and lightweight, making it comfortable to wear all day. The battery lasts several days, and the notifications from my phone come through perfectly.",
    hasMedia: true,
    videoIndex: 5,
    avatar: 10,
  },
];
